create sequence answer_seq start with 1 increment by 50;
create sequence category_seq start with 1 increment by 50;
create sequence difficulty_seq start with 1 increment by 50;
create sequence player_seq start with 1 increment by 50;
create sequence question_seq start with 1 increment by 50;
create sequence quizz_seq start with 1 increment by 50;
create sequence session_seq start with 1 increment by 50;
create table answer (id integer not null, value varchar(100) not null, primary key (id));
create table answer_questions (answers_id integer not null, questions_id integer not null);
create table category (id integer not null, value varchar(100) not null, primary key (id));
create table category_questions (categories_id integer not null, questions_id integer not null);
create table difficulty (id integer not null, value varchar(100) not null, primary key (id));
create table player (id integer not null, name varchar(100) not null, primary key (id));
create table player_sessions (players_id integer not null, sessions_id integer not null);
create table question (difficulty_id integer, id integer not null, value varchar(100) not null, primary key (id));
create table question_quizzs (questions_id integer not null, quizzs_id integer not null);
create table quizz (category_id integer, difficulty_id integer, id integer not null, description varchar(100) not null, title varchar(100) not null, primary key (id));
create table session (id integer not null, quizz_id integer, mode_de_jeu varchar(100) not null, primary key (id));
alter table if exists answer_questions add constraint FKg70ha8xddeo1ixmsf61g9s76 foreign key (questions_id) references question;
alter table if exists answer_questions add constraint FKhtcblk77kpjrpm16hmien50s9 foreign key (answers_id) references answer;
alter table if exists category_questions add constraint FKqw4ownt24a0q8l1df30tb6hwk foreign key (questions_id) references question;
alter table if exists category_questions add constraint FK41lu2alpmkkaq22d8et1bp7g1 foreign key (categories_id) references category;
alter table if exists player_sessions add constraint FK6s92oinsbrljdqefh1xeb9hc5 foreign key (sessions_id) references session;
alter table if exists player_sessions add constraint FK47vxnfxj5p7v78wriu922bbcv foreign key (players_id) references player;
alter table if exists question add constraint FK49hc407bo94aa1s6j9wtu4leu foreign key (difficulty_id) references difficulty;
alter table if exists question_quizzs add constraint FKdfqta556q7g0trrgl5oshhgat foreign key (quizzs_id) references quizz;
alter table if exists question_quizzs add constraint FK30aojumv5pc50nvs6cmicntb foreign key (questions_id) references question;
alter table if exists quizz add constraint FKpnavgw8uv1qpvl18m9jwls5xw foreign key (category_id) references category;
alter table if exists quizz add constraint FKfywvkmjqlnfbwm1k82htt1xka foreign key (difficulty_id) references difficulty;
alter table if exists session add constraint FKqgquk0sgyfvx21nch69sp77f6 foreign key (quizz_id) references quizz;
create sequence answer_seq start with 1 increment by 50;
create sequence category_seq start with 1 increment by 50;
create sequence difficulty_seq start with 1 increment by 50;
create sequence player_seq start with 1 increment by 50;
create sequence question_seq start with 1 increment by 50;
create sequence quizz_seq start with 1 increment by 50;
create sequence session_seq start with 1 increment by 50;
create table answer (id integer not null, value varchar(100) not null, primary key (id));
create table answer_questions (answers_id integer not null, questions_id integer not null);
create table category (id integer not null, value varchar(100) not null, primary key (id));
create table category_questions (categories_id integer not null, questions_id integer not null);
create table difficulty (id integer not null, value varchar(100) not null, primary key (id));
create table player (id integer not null, name varchar(100) not null, primary key (id));
create table player_sessions (players_id integer not null, sessions_id integer not null);
create table question (difficulty_id integer, id integer not null, value varchar(100) not null, primary key (id));
create table question_quizzs (questions_id integer not null, quizzs_id integer not null);
create table quizz (category_id integer, difficulty_id integer, id integer not null, description varchar(100) not null, title varchar(100) not null, primary key (id));
create table session (id integer not null, quizz_id integer, mode_de_jeu varchar(100) not null, primary key (id));
alter table if exists answer_questions add constraint FKg70ha8xddeo1ixmsf61g9s76 foreign key (questions_id) references question;
alter table if exists answer_questions add constraint FKhtcblk77kpjrpm16hmien50s9 foreign key (answers_id) references answer;
alter table if exists category_questions add constraint FKqw4ownt24a0q8l1df30tb6hwk foreign key (questions_id) references question;
alter table if exists category_questions add constraint FK41lu2alpmkkaq22d8et1bp7g1 foreign key (categories_id) references category;
alter table if exists player_sessions add constraint FK6s92oinsbrljdqefh1xeb9hc5 foreign key (sessions_id) references session;
alter table if exists player_sessions add constraint FK47vxnfxj5p7v78wriu922bbcv foreign key (players_id) references player;
alter table if exists question add constraint FK49hc407bo94aa1s6j9wtu4leu foreign key (difficulty_id) references difficulty;
alter table if exists question_quizzs add constraint FKdfqta556q7g0trrgl5oshhgat foreign key (quizzs_id) references quizz;
alter table if exists question_quizzs add constraint FK30aojumv5pc50nvs6cmicntb foreign key (questions_id) references question;
alter table if exists quizz add constraint FKpnavgw8uv1qpvl18m9jwls5xw foreign key (category_id) references category;
alter table if exists quizz add constraint FKfywvkmjqlnfbwm1k82htt1xka foreign key (difficulty_id) references difficulty;
alter table if exists session add constraint FKqgquk0sgyfvx21nch69sp77f6 foreign key (quizz_id) references quizz;
